spring:
  profiles:
    active: local
# Global configuration
---
spring:
  main:
    banner-mode: "off"

server:
  address: 127.0.0.1
  port: 8020
---
spring:
  main:
    banner-mode: "off"
  application:
    name: Core-local-service
  config:
    activate:
      on-profile: local
server:
  address: 127.0.0.1
  port: 8020